[server]
use-ipv4=yes
use-ipv6=yes
check-response-ttl=no
use-iff-running=yes
enable-dbus=yes
allow-point-to-point=no
disallow-other-stacks=no
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=no

[publish]
disable-publishing=yes
publish-addresses=no
publish-hinfo=no
publish-workstation=no
publish-domain=no

[reflector]
enable-reflector=no
